name: Upload Artifact from Branch Folder

on:
  pull_request:
    branches:
      - dev

permissions:
  pull-requests: write
  contents: read

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: testApk
        path: testApk/app-debug.apk

    - name: Post artifact link to PR
      uses: actions/github-script@v6
      with:
       script: |
         const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId
          });
         const artifact = artifacts.data.artifacts.find(a => a.name === 'testApk');
         if (artifact) {
             const artifactUrl = `${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${artifact.id}`;
             github.rest.issues.createComment({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `APK файл для этого PR можно скачать [здесь](${artifactUrl}).`
            });
         } else {
             console.log('Артефакт не найден');
         }