name: Build Debug APK

on:
  pull_request:
    branches:
      - dev

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Check out the code
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Grant execute permission for gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build the project
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Upload the APK as an artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # Make Comment
      - name: Post artifact link to PR
        uses: actions/github-script@v6
        with:
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.runId
             });
            const artifact = artifacts.data.artifacts.find(a => a.name === 'debug-apk');
            if (artifact) {
                const artifactUrl = `${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${artifact.id}`;
                github.rest.issues.createComment({
                 issue_number: ${{ github.event.pull_request.number }},
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 body: `APK файл для этого PR можно скачать [здесь](${artifactUrl}).`
               });
            } else {
                console.log('Артефакт не найден');
            }